### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np
a = np.array([1,2,3,4,5,6]) # This is alos called vector
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [2]:
# 2D
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # This is also called Matrix
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
#3D
c = np.array([[[1,2],[3,4]],[[5,6,],[7,8]]]) # This is also called Tensor
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
#dtype
d = np.array([1,2,3,4,5],dtype=float)
print(d)

[1. 2. 3. 4. 5.]


In [5]:
e = np.array([1,2,3,4,5],dtype=bool)
print(e)

[ True  True  True  True  True]


In [6]:
f = np.array([1,2,3,4,5],dtype=complex)
print(f)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


## np.arange() function is usded to create  given range numbers.

In [7]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [14]:
# np.ones() function
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
# np.zeros()
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# np.random
np.random.random((3,4))

array([[0.39814851, 0.25390667, 0.73823429, 0.08314632],
       [0.45690291, 0.03863496, 0.97538515, 0.63669858],
       [0.9638158 , 0.09648905, 0.42713514, 0.53343111]])

In [17]:
# np.linspace
np.linspace(1,10,20,dtype=int)

array([ 1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
        9,  9, 10])

In [18]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [19]:
a1 = np.arange(10)
a2 = np.arange(12, dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [20]:
#ndiim
# a1.ndim
# a2.ndim
a3.ndim

3

In [21]:
# shape
# a1.shape
# a2.shape
a3.shape

(2, 2, 2)

In [22]:
# size
# a1.size
# a2.size
a3.size

8

In [23]:
#itemsize
# a1.itemsize
# a2.itemsize
a3.itemsize

8

In [24]:
#dtype
# print(a1.dtype)
# print(a2.dtype)
print(a3.dtype)


int64


# Changing Datatype

In [25]:
#astype
# a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [26]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [27]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
# scalar operations


# arithmetic
# a1 * 2
# a1 + 2
# a1 - 2
# a1 /2
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [30]:
# relational
# a2 > 15
# a2 == 15
a2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [31]:
# vector operations
# arithmetic
a1 + a2
# a1 - a2
# a1 * a2
# a1 / a2
# a1 ** a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array Functions

In [32]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[16., 82., 46.],
       [13., 44., 20.],
       [77., 22., 33.]])

In [33]:
# max/min/sum/prod

# 0 -> column and 1-> row

# np.max(a1)
# np.min(a1)
# np.sum(a1)
# np.prod(a1)

# np.max(a1,axis=0)
# np.min(a1,axis=1)
np.sum(a1,axis=1)
# np.prod(a1,axis=1)

array([144.,  77., 132.])

In [34]:
# mean/median/std/var

# np.mean(a1)
# np.median(a1)
# np.std(a1)
# np.var(a1)

# np.mean(a1,axis=0)
# np.median(a1,axis=0)
# np.std(a1,axis=0)
# np.var(a1,axis=0)

np.mean(a1,axis=1)
np.median(a1,axis=1)
np.std(a1,axis=1)
np.var(a1,axis=1)



array([728.        , 176.22222222, 564.66666667])

In [35]:
# trignomoetric functions
np.sin(a1)

array([[-0.28790332,  0.31322878,  0.90178835],
       [ 0.42016704,  0.01770193,  0.91294525],
       [ 0.99952016, -0.00885131,  0.99991186]])

In [36]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(4,3)

np.dot(a2,a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [37]:
# log and exponents

#a1
# np.log(a1)
np.exp(a1)

array([[8.88611052e+06, 4.09399696e+35, 9.49611942e+19],
       [4.42413392e+05, 1.28516001e+19, 4.85165195e+08],
       [2.75851345e+33, 3.58491285e+09, 2.14643580e+14]])

In [38]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)

array([[62., 73., 22.],
       [36., 54., 55.]])

## Indexing And Slicing

In [39]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1[0]

0

In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
# a2[1][2]
a2[1,2]

6

In [44]:
a2[2,3]

11

In [45]:
a2[1,0]

4

In [46]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
a3[1,0,1]

5

In [48]:
a3[0,1,0]

2

In [49]:
a3[0,0,0]

0

In [50]:
a3[0,1,0]

2

In [51]:
a3[1,1,0]

6

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1[2:5]

array([2, 3, 4])

In [54]:
a1[2:5:2]

array([2, 4])

In [55]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
a2[0,:]

array([0, 1, 2, 3])

In [57]:
a2[:,2]

array([ 2,  6, 10])

In [58]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [59]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [60]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [61]:
a2[1:2,0::3]

array([[4, 7]])

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [64]:
a3 = np.arange(27).reshape(3,3,3)

In [65]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [67]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [69]:
a3[0,1,:]

array([3, 4, 5])

In [70]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [71]:
a3[1,:,1:2]

array([[10],
       [13],
       [16]])

In [72]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [73]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
a3[::2,0:1,::2]

array([[[ 0,  2]],

       [[18, 20]]])

## Iterating

In [75]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [76]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [77]:
a3
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [78]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [79]:
# reshape


In [81]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [85]:
# ravel

a2.ravel() # ravel fnction is used to convert any 2D or 3D martix in 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Stacking

In [ ]:
# horitonzal stacking
